### ISSUE TITLE
resnet_1d error RuntimeError: Given groups=1, weight of size [128, 1, 3, 3], expected input[16, 3, 224, 224] to have 1 channels, but got 3 channels instead

### ISSUE THREAD

**Issue by khawar-islam** [mwritescode/smart-contracts-vulnerabilities#3]
Dear @mwritescode 

I am training on `resnet_1d` but it gives an error maybe Pytorch version problem. Do you know how to solve it?

.YAML File

```
DATASET:
  AUGUMENTATION: false
  BINARY_LABELS: false
  IMG_SHAPE: 224
  LOADER:
    BATCH_SIZE: 16
  MAX_SEQ_LEN: 512
  NORMALIZE: true
  RGB_IMAGES: true
  USE_IMAGENET_STATS: false
MODEL:
  NAME: 1d_resnet
  N_CLASSES: 5
TRAINING:
  CHECKPOINTS:
    DECREASING: false
    MONITOR: val_acc
    PATH: checkpoints/1d_resnet.pkl
    USE: true
  EARLY_STOPPING:
    DECREASING: false
    MONITOR: val_acc
    PATIENCE: 10
    USE: true
  LAYERS_TO_FINETUNE: 6
  LOGGER:
    RUN_TAG: <config_name>
    USE: true
  LOSS: binary_crossentropy
  N_EPOCHS: 100
  OPTIMIZER:
    LR: 0.001
    MOMENTUM: 0.9
    NAME: sgd
    USE_WEIGHTS: false
    WEIGHT_DECAY: 0.0001
  TRACK_METRICS:
    AVERAGE:
    - macro
    - micro
    NAMES:
    - f1
    - precision
    - recall
    USE: true
  TRAIN_FROM_SCRATCH: false

```
`RuntimeError: Given groups=1, weight of size [128, 1, 3, 3], expected input[16, 3, 224, 224] to have 1 channels, but got 3 channels instead`
